import { Upgrade } from './atomFactory';

export const Upgrades: Record<string, Upgrade> = {
	forceful_clicking: {
		id: 'forceful_clicking',
		isBaseUpgrade: true,
		name: `Forceful Clicking`,
		description: `Maybe if you click harder...`,
		cost: 25,
		costMult: 1.75,
		clickPowerIncrease: 0.25,
		clickPowerMultiplierIncrease: 0,
		level: 0,
		maxLevel: 999,
		currencyPerSecond: 0,
		firstPurchase: false,
		relatedUpgrades: {
			forceful_clicking_ii: {
				id: 'forceful_clicking_ii',
				isBaseUpgrade: false,
				name: `Forceful Clicking II`,
				description: `Maybe if you click even harder...`,
				cost: 55,
				costMult: 2.25,
				clickPowerIncrease: 0.35,
				clickPowerMultiplierIncrease: 0,
				level: 0,
				maxLevel: 99,
				currencyPerSecond: 0,
				firstPurchase: false,
				relatedUpgrades: {},
			},
			forceful_clicking_iii: {
				id: 'forceful_clicking_iii',
				isBaseUpgrade: false,
				name: `Forceful Clicking III`,
				description: `Maybe if you click EVEN harder...`,
				cost: 85,
				costMult: 5.25,
				clickPowerIncrease: 0.55,
				clickPowerMultiplierIncrease: 0,
				level: 0,
				maxLevel: 99,
				currencyPerSecond: 0,
				firstPurchase: false,
				relatedUpgrades: {},
			},
		},
	},
	patience: {
		id: 'patience',
		isBaseUpgrade: true,
		name: `Patience`,
		description: `
		They say a watched pot never boils... Well, maybe if you buy this upgrade and stare at the screen for long enough, something will happen.
		`,
		cost: 60,
		costMult: 5.25,
		clickPowerIncrease: 0,
		clickPowerMultiplierIncrease: 0,
		level: 0,
		maxLevel: 99,
		currencyPerSecond: 0.125,
		firstPurchase: false,
		relatedUpgrades: {
			patience_ii: {
				id: 'patience_ii',
				isBaseUpgrade: false,
				name: `Patience II`,
				description: `
		They say a watched pot never boils... Well, maybe if you buy this upgrade and stare at the screen for just a little longer, something will happen.
		`,
				cost: 85,
				costMult: 5.25,
				clickPowerIncrease: 0,
				clickPowerMultiplierIncrease: 0,
				level: 0,
				maxLevel: 99,
				currencyPerSecond: 0.25,
				firstPurchase: false,
				relatedUpgrades: {},
			},
			patience_iii: {
				id: 'patience_iii',
				isBaseUpgrade: false,
				name: `Patience III`,
				description: `
		They say a watched pot never boils... Well, maybe if you buy this upgrade and stare at the screen for just a tiny bit longer, something will happen.
		`,
				cost: 105,
				costMult: 5.25,
				clickPowerIncrease: 0,
				clickPowerMultiplierIncrease: 0,
				level: 0,
				maxLevel: 99,
				currencyPerSecond: 0.5,
				firstPurchase: false,
				relatedUpgrades: {},
			},
		},
	},
};

export const PrestigeUpgrades: Record<string, Upgrade> = {
	better_keyboard: {
		id: 'better_keyboard',
		isBaseUpgrade: true,
		name: 'Better Keyboard',
		description: `You splurged and bought the newest mechanical keyboard you could find... Let's see if it helps!`,
		cost: 100,
		costMult: 5,
		clickPowerIncrease: 5,
		clickPowerMultiplierIncrease: 0,
		level: 0,
		maxLevel: 5,
		currencyPerSecond: 0,
		firstPurchase: false,
		relatedUpgrades: {
			better_keyboard_ii: {
				id: 'better_keyboard_ii',
				isBaseUpgrade: false,
				name: 'Better Keyboard II',
				description: `You splurged and bought the newest mechanical keyboard you could find... The last one seemed to help, so this one HAS to help...`,
				cost: 1000,
				costMult: 5,
				clickPowerIncrease: 10,
				clickPowerMultiplierIncrease: 0,
				level: 0,
				maxLevel: 3,
				currencyPerSecond: 0,
				firstPurchase: false,
				relatedUpgrades: {},
			},
			better_keyboard_iii: {
				id: 'better_keyboard_iii',
				isBaseUpgrade: false,
				name: 'Better Keyboard III',
				description: `This is the nicest keyboard money can buy.`,
				cost: 10000,
				costMult: 1,
				clickPowerIncrease: 75,
				clickPowerMultiplierIncrease: 8,
				level: 0,
				maxLevel: 1,
				currencyPerSecond: 0,
				firstPurchase: false,
				relatedUpgrades: {},
			},
		},
	},
	accidental_mutation: {
		id: 'accidental_mutation',
		isBaseUpgrade: true,
		name: 'Accidental Mutation',
		description: `You woke up with a few extra fingers today...`,
		cost: 200,
		costMult: 5,
		clickPowerIncrease: 0,
		clickPowerMultiplierIncrease: 2,
		level: 0,
		maxLevel: 5,
		currencyPerSecond: 0,
		firstPurchase: false,
		relatedUpgrades: {
			accidental_mutation_ii: {
				id: 'accidental_mutation_ii',
				isBaseUpgrade: false,
				name: 'Accidental Mutation II',
				description: `You woke up with a few extra toes today...`,
				cost: 2000,
				costMult: 5,
				clickPowerIncrease: 5,
				clickPowerMultiplierIncrease: 4,
				level: 0,
				maxLevel: 3,
				currencyPerSecond: 0,
				firstPurchase: false,
			},
			accidental_mutation_iii: {
				id: 'accidental_mutation_iii',
				isBaseUpgrade: false,
				name: 'Accidental Mutation III',
				description: `You woke up with a few extra limbs today...`,
				cost: 20000,
				costMult: 1,
				clickPowerIncrease: 25,
				clickPowerMultiplierIncrease: 8,
				level: 0,
				maxLevel: 1,
				currencyPerSecond: 0,
				firstPurchase: false,
			},
		},
	},
};
